### ISSUE TITLE
Unable to build image

### ISSUE THREAD

**Issue by BRAVO68WEB** [bcomnes/raspi-packer#41]
I forked your repo and was trying to build my own rpi 5 image but I got this error

Code :- https://github.com/bravo-on-rpi/raspi-packer/tree/b68/rpi

```
Error: Failed to initialize build "arm"
The builder arm is unknown by Packer, and is likely part of a plugin that is not
installed.
You may find the needed plugin along with installation instructions documented
on the Packer integrations page.
```

My change are located in `b68/rpi` branch
I didn't changed anything in `master` branch

I got the exact same error on actions on both branchs

Can you please help me figure it out?

**Comment by BRAVO68WEB** [comment]
This is my action output log
https://github.com/bravo-on-rpi/raspi-packer/actions/runs/9534153936/job/26278246332

**Comment by bcomnes** [comment]
Packer is an annoying target to build with and always pushed out breaking changes. Looks like the last successful build used packer_1.10.3_linux_amd64.zip, but is now failing with Downloading packer_1.11.0_linux_amd64.zip.

Maybe try pinning that version down in the install packer action and see if that fixes it, or figure out what needs to change to work with the updated version if you are adventurous.

**Comment by BRAVO68WEB** [comment]
Ok 🙂

**Comment by bcomnes** [comment]
I finally needed a new image and fixed the build. Builds are green again if you are curious: https://github.com/bcomnes/raspi-packer/actions/runs/10067678336

Packer seems incapable of not breaking at least once a year, including all previous versions that were working, so if you do go this route, expect to debug at least once a year or whenever you need to generate images.  Thinking of just extracting quemu functionality and setup scripts and removing the packer portion if it happens one more time. 

The fix was that the builder plugin needed to be updated to track some really dubious plugin systems updates that landed in packer (and also back ported to a bunch of older versions for some reason). Check the git history if you are curious.
